#---- GENERAL
GPU: 0
VERBOSE: True

#---- PATHS
MODEL_DIR: 'bin/'
RESULTS_DIR: 'results/'
LOG_DIR: 'logs/'
MODEL_NAME: 'AcT'

#---- DATASET
SPLITS: 1
FOLDS: 5
SEEDS: [11331, 11435, 12123, 53453, 24234, 42344, 65747, 84443, 29345, 99543]
VAL_SIZE: 0.1
CHANNELS: 4
SUBSAMPLE: 1
DATASET: 'vitpose'
LEGACY: False
vitpose:
    KEYPOINTS: 15 
    CLASSES: 10
    FRAMES: 30

LABELS: ['carry','doffing','donning','drop-trash','pu-onehand','pu-twohands','sit-down','stand-up','throw','walk-around']


#---- AUGMENTATION
FLIP_P: 0.6
RN_STD: 0.03

#---- MODEL
#PATCH_SIZE: 1
MODEL_SIZE: 'base'
POS_EMB: #'utils/pos_emb.npy'
base:
    N_HEADS: 3
    N_LAYERS: 6
    EMBED_DIM: 192
    DROPOUT: 0.3
    MLP: 256

#---- TRAINING SETTINGS 
SCHEDULER: True
N_EPOCHS: 500       
BATCH_SIZE: 64 
WEIGHT_DECAY: 0.0001  
WARMUP_PERC: 0.3
STEP_PERC: 0.8 
LR_MULT: 1

#---- RANDOM SEARCH
N_TRIALS: 5